package com.flinksqlfiddle.api;

import com.flinksqlfiddle.api.dto.BuildInfoResponse;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Reports which build is deployed (git commit, branch, build time), read from the
 * {@code build-info.properties} generated by the Gradle {@code generateBuildInfo} task.
 * Falls back to {@code "dev"} when the file is absent (e.g. running from an IDE).
 */
@Path("/api")
@Produces(MediaType.APPLICATION_JSON)
public class BuildInfoResource {

    private static final Logger log = LoggerFactory.getLogger(BuildInfoResource.class);

    private static final BuildInfoResponse BUILD_INFO = load();

    @GET
    @Path("/build-info")
    public BuildInfoResponse buildInfo() {
        return BUILD_INFO;
    }

    private static BuildInfoResponse load() {
        Properties props = new Properties();
        try (InputStream in = BuildInfoResource.class.getResourceAsStream("/build-info.properties")) {
            if (in != null) {
                props.load(in);
            } else {
                log.info("build-info.properties not found on classpath; reporting dev build");
            }
        } catch (IOException e) {
            log.warn("Failed to read build-info.properties: {}", e.getMessage());
        }
        return new BuildInfoResponse(
                props.getProperty("build.commit", "dev"),
                props.getProperty("build.commitFull", "dev"),
                props.getProperty("build.branch", "unknown"),
                props.getProperty("build.version", "unknown"),
                props.getProperty("build.time", "unknown")
        );
    }
}
